[Thu, 05 May 16 15:06:24 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/app/controllers/IndexController.php(19): BaseController->get_request_param('client_version', 'string', true)
#1 [internal function]: IndexController->IndexAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/public/index.php(38): Phalcon\Mvc\Application->handle()
#4 {main}
[Thu, 05 May 16 19:44:47 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/IndexController.php(19): BaseController->get_request_param('client_version', 'string', true)
#1 [internal function]: IndexController->IndexAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(34): Phalcon\Mvc\Application->handle()
#4 {main}
[Thu, 05 May 16 20:08:51 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('Action 'index' ...', 5)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(34): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:08:55 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('Action 'index' ...', 5)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(34): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:12:10 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('Action 'index' ...', 5)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(34): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:13:49 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('Action 'index' ...', 5)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(34): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:13:53 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('Action 'index' ...', 5)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(34): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:16:17 +0800][NOTICE]: [HttpError]: #0 [internal function]: LoginController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(37): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:16:44 +0800][NOTICE]: [HttpError]: #0 [internal function]: LoginController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:16:58 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/LoginController.php(26): BaseController->get_or_fail(Array, 'uid', 'string')
#1 [internal function]: LoginController->IndexAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#4 {main}
[Thu, 05 May 16 20:17:04 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/LoginController.php(27): BaseController->get_or_fail(Array, 'source', 'string')
#1 [internal function]: LoginController->IndexAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#4 {main}
[Thu, 05 May 16 21:16:12 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 21:16:48 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDO->query('SELECT `tb_news...')
#1 [internal function]: Phalcon\Db\Adapter\Pdo->query('SELECT `tb_news...', NULL, NULL)
#2 [internal function]: Phalcon\Mvc\Model\Query->_executeSelect(Array, NULL, NULL)
#3 [internal function]: Phalcon\Mvc\Model\Query->execute()
#4 /home/work/banews-server/1/app/models/NewsImage.php(28): Phalcon\Mvc\Model::find(Array)
#5 /home/work/banews-server/1/app/controllers/NewsController.php(27): NewsImage::getImagesOfNews(NULL)
#6 [internal function]: NewsController->DetailAction()
#7 [internal function]: Phalcon\Dispatcher->dispatch()
#8 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#9 {main}
[Thu, 05 May 16 21:26:00 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#4 {main}
[Thu, 05 May 16 21:26:24 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#4 {main}
[Thu, 05 May 16 21:26:28 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(94): BaseController->get_or_fail(Array, 'news_id', 'string')
#1 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#2 [internal function]: UserController->CommentAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#5 {main}
[Thu, 05 May 16 21:26:44 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(95): BaseController->get_or_fail(Array, 'comment_detail', 'string')
#1 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#2 [internal function]: UserController->CommentAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#5 {main}
[Thu, 05 May 16 21:27:02 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(95): BaseController->get_or_fail(Array, 'comment_detail', 'string')
#1 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#2 [internal function]: UserController->CommentAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#5 {main}
[Fri, 06 May 16 11:12:49 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#3 {main}
[Fri, 06 May 16 11:13:00 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#3 {main}
[Fri, 06 May 16 11:14:00 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#3 {main}
[Fri, 06 May 16 11:19:17 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#3 {main}
[Fri, 06 May 16 11:38:04 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Model\Query->parse()
#1 /home/work/banews-server/1/app/controllers/NewsController.php(74): Phalcon\Mvc\Model\Query->execute()
#2 [internal function]: NewsController->likeAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#5 {main}
[Fri, 06 May 16 11:38:27 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Model\Manager->load('tb_news', true)
#1 [internal function]: Phalcon\Mvc\Model\Query->_prepareUpdate()
#2 [internal function]: Phalcon\Mvc\Model\Query->parse()
#3 /home/work/banews-server/1/app/controllers/NewsController.php(74): Phalcon\Mvc\Model\Query->execute()
#4 [internal function]: NewsController->likeAction()
#5 [internal function]: Phalcon\Dispatcher->dispatch()
#6 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#7 {main}
[Fri, 06 May 16 16:23:09 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('Action 'index' ...', 5)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#3 {main}
[Fri, 06 May 16 16:23:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('CommentControll...', 2)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#3 {main}
[Fri, 06 May 16 16:23:38 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(35): BaseController->get_request_param('news_id', 'string', true)
#1 /home/work/banews-server/1/app/controllers/UserController.php(16): UserController->getComments()
#2 [internal function]: UserController->CommentAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#5 {main}
[Fri, 06 May 16 16:34:36 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 16:35:05 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 16:35:11 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(59): BaseController->get_or_fail(Array, 'news_id', 'string')
#1 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#2 [internal function]: UserController->CommentAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#5 {main}
[Fri, 06 May 16 16:35:27 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(60): BaseController->get_or_fail(Array, 'comment_detail', 'string')
#1 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#2 [internal function]: UserController->CommentAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#5 {main}
[Fri, 06 May 16 17:42:01 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(51): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 17:43:46 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(51): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 17:44:23 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(51): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 17:47:37 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(50): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 17:48:18 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(50): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 17:48:51 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(50): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 17:52:11 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(50): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 18:04:36 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(51): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 18:04:56 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(52): Phalcon\Mvc\Application->handle()
#4 {main}
[Sat, 07 May 16 16:24:14 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#3 {main}
[Sat, 07 May 16 16:24:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#3 {main}
[Sat, 07 May 16 16:24:46 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#3 {main}
[Sat, 07 May 16 16:25:09 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#3 {main}
[Sat, 07 May 16 16:26:12 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/NewsController.php(75): BaseController->get_request_param('channel_id', 'int', true)
#1 [internal function]: NewsController->listAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#4 {main}
[Sun, 08 May 16 15:14:53 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDO->__construct('mysql:host=root...', 'root', 'MhxzKhl-Happy!@...', Array)
#1 [internal function]: Phalcon\Db\Adapter\Pdo->connect(Array)
#2 /home/work/banews-server/1/app/config/services.php(40): Phalcon\Db\Adapter\Pdo->__construct(Array)
#3 [internal function]: {closure}()
#4 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#5 [internal function]: Phalcon\Di->get('db', NULL)
#6 [internal function]: Phalcon\Di->getShared('db')
#7 [internal function]: Phalcon\Mvc\Model\Manager->_getConnection(Object(Comment), NULL)
#8 [internal function]: Phalcon\Mvc\Model\Manager->getReadConnection(Object(Comment))
#9 [internal function]: Phalcon\Mvc\Model->getReadConnection()
#10 [internal function]: Phalcon\Mvc\Model\MetaData\Strategy\Introspection->getMetaData(Object(Comment), Object(Phalcon\Di\FactoryDefault))
#11 [internal function]: Phalcon\Mvc\Model\MetaData->_initialize(Object(Comment), 'comment-tb_comm...', 'tb_comment', '')
#12 [internal function]: Phalcon\Mvc\Model\MetaData->readMetaData(Object(Comment))
#13 [internal function]: Phalcon\Mvc\Model\MetaData->hasAttribute(Object(Comment), 'news_id')
#14 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array)
#15 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true)
#16 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array)
#17 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect()
#18 [internal function]: Phalcon\Mvc\Model\Query->parse()
#19 [internal function]: Phalcon\Mvc\Model\Query->execute(Array, NULL)
#20 [internal function]: Phalcon\Mvc\Model::_groupResult('COUNT', 'rowcount', Array)
#21 /home/work/banews-server/1/app/models/Comment.php(59): Phalcon\Mvc\Model::count(Array)
#22 /home/work/banews-server/1/app/controllers/NewsController.php(33): Comment::getCount('1001939')
#23 [internal function]: NewsController->DetailAction()
#24 [internal function]: Phalcon\Dispatcher->dispatch()
#25 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#26 {main}
[Sun, 08 May 16 15:16:17 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(24): UserController->postCollect()
#1 [internal function]: UserController->CollectAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#4 {main}
[Sun, 08 May 16 15:16:34 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(24): UserController->postCollect()
#1 [internal function]: UserController->CollectAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#4 {main}
[Sun, 08 May 16 15:16:44 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(24): UserController->postCollect()
#1 [internal function]: UserController->CollectAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#4 {main}
[Sun, 08 May 16 15:25:40 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(28): UserController->delCollect()
#1 [internal function]: UserController->CollectAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#4 {main}
[Sun, 08 May 16 15:26:01 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDO->exec('DELETE FROM tb_...')
#1 /home/work/banews-server/1/app/controllers/UserController.php(192): Phalcon\Db\Adapter\Pdo->execute('DELETE FROM tb_...')
#2 /home/work/banews-server/1/app/controllers/UserController.php(28): UserController->delCollect()
#3 [internal function]: UserController->CollectAction()
#4 [internal function]: Phalcon\Dispatcher->dispatch()
#5 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#6 {main}
[Sun, 08 May 16 15:37:18 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDO->__construct('mysql:host=10.8...', 'root', 'MhxzKhl-Happy', Array)
#1 [internal function]: Phalcon\Db\Adapter\Pdo->connect(Array)
#2 /home/work/banews-server/1/app/config/services.php(40): Phalcon\Db\Adapter\Pdo->__construct(Array)
#3 [internal function]: {closure}()
#4 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#5 [internal function]: Phalcon\Di->get('db', NULL)
#6 [internal function]: Phalcon\Di->getShared('db')
#7 [internal function]: Phalcon\Mvc\Model\Manager->_getConnection(Object(Collect), NULL)
#8 [internal function]: Phalcon\Mvc\Model\Manager->getReadConnection(Object(Collect))
#9 [internal function]: Phalcon\Mvc\Model->getReadConnection()
#10 [internal function]: Phalcon\Mvc\Model\MetaData\Strategy\Introspection->getMetaData(Object(Collect), Object(Phalcon\Di\FactoryDefault))
#11 [internal function]: Phalcon\Mvc\Model\MetaData->_initialize(Object(Collect), 'collect-tb_coll...', 'tb_collect', '')
#12 [internal function]: Phalcon\Mvc\Model\MetaData->readMetaData(Object(Collect))
#13 [internal function]: Phalcon\Mvc\Model\MetaData->hasAttribute(Object(Collect), 'user_id')
#14 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array)
#15 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true)
#16 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array)
#17 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect()
#18 [internal function]: Phalcon\Mvc\Model\Query->parse()
#19 [internal function]: Phalcon\Mvc\Model\Query->execute()
#20 /home/work/banews-server/1/app/models/Collect.php(47): Phalcon\Mvc\Model::find(Array)
#21 /home/work/banews-server/1/app/controllers/UserController.php(160): Collect::getAll('24', '', '')
#22 /home/work/banews-server/1/app/controllers/UserController.php(26): UserController->getCollect()
#23 [internal function]: UserController->CollectAction()
#24 [internal function]: Phalcon\Dispatcher->dispatch()
#25 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#26 {main}
[Sun, 08 May 16 15:54:48 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDO->exec('DELETE FROM tb_...')
#1 /home/work/banews-server/1/app/controllers/UserController.php(192): Phalcon\Db\Adapter\Pdo->execute('DELETE FROM tb_...')
#2 /home/work/banews-server/1/app/controllers/UserController.php(28): UserController->delCollect()
#3 [internal function]: UserController->CollectAction()
#4 [internal function]: Phalcon\Dispatcher->dispatch()
#5 /home/work/banews-server/1/public/index.php(59): Phalcon\Mvc\Application->handle()
#6 {main}
[Mon, 09 May 16 12:17:00 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 12:17:26 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/NewsController.php(77): BaseController->get_request_param('channel_id', 'int', true)
#1 [internal function]: NewsController->listAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#4 {main}
[Mon, 09 May 16 12:52:50 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\Db\Adapter\Pdo->executePrepared(Object(PDOStatement), Array, Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo->query('SELECT `tb_news...', Array, Array)
#3 [internal function]: Phalcon\Mvc\Model\Query->_executeSelect(Array, Array, Array)
#4 [internal function]: Phalcon\Mvc\Model\Query->execute()
#5 /home/work/banews-server/1/app/models/News.php(88): Phalcon\Mvc\Model::findFirst(Array)
#6 /home/work/banews-server/1/app/controllers/NewsController.php(86): News::getBySign(Array)
#7 [internal function]: NewsController->listAction()
#8 [internal function]: Phalcon\Dispatcher->dispatch()
#9 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#10 {main}
[Mon, 09 May 16 12:53:25 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\Db\Adapter\Pdo->executePrepared(Object(PDOStatement), Array, Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo->query('SELECT `tb_news...', Array, Array)
#3 [internal function]: Phalcon\Mvc\Model\Query->_executeSelect(Array, Array, Array)
#4 [internal function]: Phalcon\Mvc\Model\Query->execute()
#5 /home/work/banews-server/1/app/models/News.php(88): Phalcon\Mvc\Model::findFirst(Array)
#6 /home/work/banews-server/1/app/controllers/NewsController.php(86): News::getBySign(Array)
#7 [internal function]: NewsController->listAction()
#8 [internal function]: Phalcon\Dispatcher->dispatch()
#9 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#10 {main}
[Mon, 09 May 16 16:32:51 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:59 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:59 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Tue, 10 May 16 13:27:13 +0800][NOTICE]: [HttpError]: #0 [internal function]: FeedbackController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Tue, 10 May 16 13:27:44 +0800][NOTICE]: [HttpError]: #0 [internal function]: FeedbackController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Tue, 10 May 16 13:41:17 +0800][NOTICE]: [HttpError]: #0 [internal function]: FeedbackController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Tue, 10 May 16 13:44:17 +0800][NOTICE]: [HttpError]: #0 [internal function]: FeedbackController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Tue, 10 May 16 13:46:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: FeedbackController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Tue, 10 May 16 13:47:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: FeedbackController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Tue, 10 May 16 13:48:37 +0800][NOTICE]: [HttpError]: #0 [internal function]: FeedbackController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Tue, 10 May 16 13:48:39 +0800][NOTICE]: [HttpError]: #0 [internal function]: FeedbackController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Tue, 10 May 16 13:48:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: FeedbackController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Tue, 10 May 16 13:50:49 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Cache\Backend\Redis->_connect()
#1 [internal function]: Phalcon\Cache\Backend\Redis->get('BA_USER__id_', 86400)
#2 [internal function]: Phalcon\Mvc\Model\Query->execute()
#3 /home/work/banews-server/1/app/models/User.php(83): Phalcon\Mvc\Model::findFirst(Array)
#4 /home/work/banews-server/1/app/controllers/FeedbackController.php(20): User::getById(NULL)
#5 [internal function]: FeedbackController->IndexAction()
#6 [internal function]: Phalcon\Dispatcher->dispatch()
#7 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#8 {main}
[Tue, 10 May 16 13:50:53 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Cache\Backend\Redis->_connect()
#1 [internal function]: Phalcon\Cache\Backend\Redis->get('BA_USER__id_', 86400)
#2 [internal function]: Phalcon\Mvc\Model\Query->execute()
#3 /home/work/banews-server/1/app/models/User.php(83): Phalcon\Mvc\Model::findFirst(Array)
#4 /home/work/banews-server/1/app/controllers/FeedbackController.php(20): User::getById(NULL)
#5 [internal function]: FeedbackController->IndexAction()
#6 [internal function]: Phalcon\Dispatcher->dispatch()
#7 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#8 {main}
[Tue, 10 May 16 13:52:03 +0800][NOTICE]: [HttpError]: #0 [internal function]: FeedbackController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Tue, 10 May 16 13:52:17 +0800][NOTICE]: [HttpError]: #0 [internal function]: FeedbackController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Tue, 10 May 16 13:52:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: FeedbackController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Wed, 11 May 16 15:43:41 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(125): BaseController->get_or_fail(Array, 'news_id', 'string')
#1 /home/work/banews-server/1/app/controllers/UserController.php(24): UserController->postCollect()
#2 [internal function]: UserController->CollectAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#5 {main}
[Wed, 11 May 16 15:43:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Model\Query->parse()
#1 [internal function]: Phalcon\Mvc\Model\Query->execute()
#2 /home/work/banews-server/1/app/models/Collect.php(48): Phalcon\Mvc\Model::find(Array)
#3 /home/work/banews-server/1/app/controllers/UserController.php(162): Collect::getAll('24', '', '')
#4 /home/work/banews-server/1/app/controllers/UserController.php(26): UserController->getCollect()
#5 [internal function]: UserController->CollectAction()
#6 [internal function]: Phalcon\Dispatcher->dispatch()
#7 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#8 {main}
[Wed, 11 May 16 15:44:14 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(160): BaseController->get_request_param('pn', 'int', 10)
#1 /home/work/banews-server/1/app/controllers/UserController.php(26): UserController->getCollect()
#2 [internal function]: UserController->CollectAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#5 {main}
[Wed, 11 May 16 15:44:42 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Model\Query->parse()
#1 [internal function]: Phalcon\Mvc\Model\Query->execute()
#2 /home/work/banews-server/1/app/models/Collect.php(48): Phalcon\Mvc\Model::find(Array)
#3 /home/work/banews-server/1/app/controllers/UserController.php(162): Collect::getAll('24', 0, 10)
#4 /home/work/banews-server/1/app/controllers/UserController.php(26): UserController->getCollect()
#5 [internal function]: UserController->CollectAction()
#6 [internal function]: Phalcon\Dispatcher->dispatch()
#7 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#8 {main}
[Fri, 13 May 16 14:50:38 +0800][NOTICE]: [NewsList][id:3fdc1608281f7e1e][policy:ExpDecay][di:][pfer:later][cnl:10003][sent:6]
[Fri, 13 May 16 14:50:45 +0800][NOTICE]: [NewsList][id:a1f7f42275982fcf][policy:ExpDecay][di:][pfer:later][cnl:10003][sent:0]
[Fri, 13 May 16 14:50:53 +0800][NOTICE]: [NewsList][id:c0326dd85d00c138][policy:ExpDecay][di:][pfer:later][cnl:10003][sent:6]
[Fri, 13 May 16 14:50:54 +0800][NOTICE]: [NewsList][id:f1b635a8e502ee1c][policy:ExpDecay][di:][pfer:later][cnl:10003][sent:0]
[Fri, 13 May 16 14:51:03 +0800][NOTICE]: [NewsList][id:b05bb0e67a46e05c][policy:ExpDecay][di:][pfer:later][cnl:10003][sent:6]
[Mon, 16 May 16 15:01:10 +0800][NOTICE]: [NewsList][id:86d744e370a85680][policy:ExpDecay][di:][pfer:later][cnl:10003][sent:14]
[Mon, 16 May 16 15:01:21 +0800][NOTICE]: [NewsList][id:658287e605b760df][policy:ExpDecay][di:][pfer:later][cnl:10003][sent:1]
[Mon, 16 May 16 15:01:27 +0800][NOTICE]: [NewsList][id:39fae6a1feb773c0][policy:ExpDecay][di:][pfer:later][cnl:10003][sent:0]
[Mon, 16 May 16 15:01:28 +0800][NOTICE]: [NewsList][id:31d0b6fc3430e52d][policy:ExpDecay][di:][pfer:later][cnl:10003][sent:0]
[Mon, 16 May 16 15:01:31 +0800][NOTICE]: [NewsList][id:190db43a0e61b483][policy:ExpDecay][di:][pfer:later][cnl:10003][sent:14]
[Mon, 16 May 16 15:03:54 +0800][NOTICE]: [NewsList][id:a4fc55c12077f71b][policy:ExpDecay][di:zhangguanxing109][pfer:later][cnl:10003][sent:1]
[Mon, 16 May 16 15:21:52 +0800][NOTICE]: [NewsList][id:e8bf3235e3b018c9][policy:ExpDecay][di:zhangguanxing109][pfer:later][cnl:10003][sent:14]
[Mon, 16 May 16 15:21:58 +0800][NOTICE]: [NewsList][id:5b408bbdd0345ea5][policy:ExpDecay][di:zhangguanxing109][pfer:later][cnl:10003][sent:1]
[Mon, 16 May 16 15:22:03 +0800][NOTICE]: [NewsList][id:da569557306c4c5d][policy:ExpDecay][di:zhangguanxing109][pfer:later][cnl:10003][sent:0]
[Mon, 16 May 16 15:22:04 +0800][NOTICE]: [NewsList][id:926e90b9bcd73ad6][policy:ExpDecay][di:zhangguanxing109][pfer:later][cnl:10003][sent:0]
[Mon, 16 May 16 15:22:05 +0800][NOTICE]: [NewsList][id:1225f8d6f62ac8cd][policy:ExpDecay][di:zhangguanxing109][pfer:later][cnl:10003][sent:0]
[Mon, 16 May 16 15:22:06 +0800][NOTICE]: [NewsList][id:8cebba098b01dce3][policy:ExpDecay][di:zhangguanxing109][pfer:later][cnl:10003][sent:0]
[Mon, 16 May 16 15:22:06 +0800][NOTICE]: [NewsList][id:8cebba098b01dce3][policy:ExpDecay][di:zhangguanxing109][pfer:later][cnl:10003][sent:0]
[Mon, 16 May 16 15:22:07 +0800][NOTICE]: [NewsList][id:75420b5de7629f73][policy:ExpDecay][di:zhangguanxing109][pfer:later][cnl:10003][sent:0]
[Mon, 16 May 16 15:22:07 +0800][NOTICE]: [NewsList][id:75420b5de7629f73][policy:ExpDecay][di:zhangguanxing109][pfer:later][cnl:10003][sent:0]
[Mon, 16 May 16 15:22:08 +0800][NOTICE]: [NewsList][id:8668057d3a789d0f][policy:ExpDecay][di:zhangguanxing109][pfer:later][cnl:10003][sent:0]
[Mon, 16 May 16 15:22:09 +0800][NOTICE]: [NewsList][id:4163146acda073dc][policy:ExpDecay][di:zhangguanxing109][pfer:later][cnl:10003][sent:0]
[Mon, 16 May 16 15:26:20 +0800][NOTICE]: [HttpError]: #0 [internal function]: FeedbackController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 16 May 16 15:26:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 16 May 16 18:15:12 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 16 May 16 18:15:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 16 May 16 18:21:54 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
