[Thu, 05 May 16 15:06:24 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/app/controllers/IndexController.php(19): BaseController->get_request_param('client_version', 'string', true)
#1 [internal function]: IndexController->IndexAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/public/index.php(38): Phalcon\Mvc\Application->handle()
#4 {main}
[Thu, 05 May 16 19:44:47 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/IndexController.php(19): BaseController->get_request_param('client_version', 'string', true)
#1 [internal function]: IndexController->IndexAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(34): Phalcon\Mvc\Application->handle()
#4 {main}
[Thu, 05 May 16 20:08:51 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('Action 'index' ...', 5)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(34): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:08:55 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('Action 'index' ...', 5)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(34): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:12:10 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('Action 'index' ...', 5)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(34): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:13:49 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('Action 'index' ...', 5)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(34): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:13:53 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('Action 'index' ...', 5)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(34): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:16:17 +0800][NOTICE]: [HttpError]: #0 [internal function]: LoginController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(37): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:16:44 +0800][NOTICE]: [HttpError]: #0 [internal function]: LoginController->IndexAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 20:16:58 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/LoginController.php(26): BaseController->get_or_fail(Array, 'uid', 'string')
#1 [internal function]: LoginController->IndexAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#4 {main}
[Thu, 05 May 16 20:17:04 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/LoginController.php(27): BaseController->get_or_fail(Array, 'source', 'string')
#1 [internal function]: LoginController->IndexAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#4 {main}
[Thu, 05 May 16 21:16:12 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#3 {main}
[Thu, 05 May 16 21:16:48 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDO->query('SELECT `tb_news...')
#1 [internal function]: Phalcon\Db\Adapter\Pdo->query('SELECT `tb_news...', NULL, NULL)
#2 [internal function]: Phalcon\Mvc\Model\Query->_executeSelect(Array, NULL, NULL)
#3 [internal function]: Phalcon\Mvc\Model\Query->execute()
#4 /home/work/banews-server/1/app/models/NewsImage.php(28): Phalcon\Mvc\Model::find(Array)
#5 /home/work/banews-server/1/app/controllers/NewsController.php(27): NewsImage::getImagesOfNews(NULL)
#6 [internal function]: NewsController->DetailAction()
#7 [internal function]: Phalcon\Dispatcher->dispatch()
#8 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#9 {main}
[Thu, 05 May 16 21:26:00 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#4 {main}
[Thu, 05 May 16 21:26:24 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#4 {main}
[Thu, 05 May 16 21:26:28 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(94): BaseController->get_or_fail(Array, 'news_id', 'string')
#1 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#2 [internal function]: UserController->CommentAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#5 {main}
[Thu, 05 May 16 21:26:44 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(95): BaseController->get_or_fail(Array, 'comment_detail', 'string')
#1 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#2 [internal function]: UserController->CommentAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#5 {main}
[Thu, 05 May 16 21:27:02 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(95): BaseController->get_or_fail(Array, 'comment_detail', 'string')
#1 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#2 [internal function]: UserController->CommentAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#5 {main}
[Fri, 06 May 16 11:12:49 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#3 {main}
[Fri, 06 May 16 11:13:00 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#3 {main}
[Fri, 06 May 16 11:14:00 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#3 {main}
[Fri, 06 May 16 11:19:17 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->DetailAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#3 {main}
[Fri, 06 May 16 11:38:04 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Model\Query->parse()
#1 /home/work/banews-server/1/app/controllers/NewsController.php(74): Phalcon\Mvc\Model\Query->execute()
#2 [internal function]: NewsController->likeAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#5 {main}
[Fri, 06 May 16 11:38:27 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Model\Manager->load('tb_news', true)
#1 [internal function]: Phalcon\Mvc\Model\Query->_prepareUpdate()
#2 [internal function]: Phalcon\Mvc\Model\Query->parse()
#3 /home/work/banews-server/1/app/controllers/NewsController.php(74): Phalcon\Mvc\Model\Query->execute()
#4 [internal function]: NewsController->likeAction()
#5 [internal function]: Phalcon\Dispatcher->dispatch()
#6 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#7 {main}
[Fri, 06 May 16 16:23:09 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('Action 'index' ...', 5)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#3 {main}
[Fri, 06 May 16 16:23:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('CommentControll...', 2)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#3 {main}
[Fri, 06 May 16 16:23:38 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(35): BaseController->get_request_param('news_id', 'string', true)
#1 /home/work/banews-server/1/app/controllers/UserController.php(16): UserController->getComments()
#2 [internal function]: UserController->CommentAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(28): Phalcon\Mvc\Application->handle()
#5 {main}
[Fri, 06 May 16 16:34:36 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 16:35:05 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 16:35:11 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(59): BaseController->get_or_fail(Array, 'news_id', 'string')
#1 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#2 [internal function]: UserController->CommentAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#5 {main}
[Fri, 06 May 16 16:35:27 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(60): BaseController->get_or_fail(Array, 'comment_detail', 'string')
#1 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#2 [internal function]: UserController->CommentAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /home/work/banews-server/1/public/index.php(35): Phalcon\Mvc\Application->handle()
#5 {main}
[Fri, 06 May 16 17:42:01 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(51): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 17:43:46 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(51): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 17:44:23 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(51): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 17:47:37 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(50): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 17:48:18 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(50): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 17:48:51 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(50): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 17:52:11 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(50): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 18:04:36 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(51): Phalcon\Mvc\Application->handle()
#4 {main}
[Fri, 06 May 16 18:04:56 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(14): UserController->postComments()
#1 [internal function]: UserController->CommentAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(52): Phalcon\Mvc\Application->handle()
#4 {main}
[Sat, 07 May 16 16:24:14 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#3 {main}
[Sat, 07 May 16 16:24:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#3 {main}
[Sat, 07 May 16 16:24:46 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#3 {main}
[Sat, 07 May 16 16:25:09 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#3 {main}
[Sat, 07 May 16 16:26:12 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/NewsController.php(75): BaseController->get_request_param('channel_id', 'int', true)
#1 [internal function]: NewsController->listAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#4 {main}
[Sun, 08 May 16 15:14:53 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDO->__construct('mysql:host=root...', 'root', 'MhxzKhl-Happy!@...', Array)
#1 [internal function]: Phalcon\Db\Adapter\Pdo->connect(Array)
#2 /home/work/banews-server/1/app/config/services.php(40): Phalcon\Db\Adapter\Pdo->__construct(Array)
#3 [internal function]: {closure}()
#4 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#5 [internal function]: Phalcon\Di->get('db', NULL)
#6 [internal function]: Phalcon\Di->getShared('db')
#7 [internal function]: Phalcon\Mvc\Model\Manager->_getConnection(Object(Comment), NULL)
#8 [internal function]: Phalcon\Mvc\Model\Manager->getReadConnection(Object(Comment))
#9 [internal function]: Phalcon\Mvc\Model->getReadConnection()
#10 [internal function]: Phalcon\Mvc\Model\MetaData\Strategy\Introspection->getMetaData(Object(Comment), Object(Phalcon\Di\FactoryDefault))
#11 [internal function]: Phalcon\Mvc\Model\MetaData->_initialize(Object(Comment), 'comment-tb_comm...', 'tb_comment', '')
#12 [internal function]: Phalcon\Mvc\Model\MetaData->readMetaData(Object(Comment))
#13 [internal function]: Phalcon\Mvc\Model\MetaData->hasAttribute(Object(Comment), 'news_id')
#14 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array)
#15 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true)
#16 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array)
#17 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect()
#18 [internal function]: Phalcon\Mvc\Model\Query->parse()
#19 [internal function]: Phalcon\Mvc\Model\Query->execute(Array, NULL)
#20 [internal function]: Phalcon\Mvc\Model::_groupResult('COUNT', 'rowcount', Array)
#21 /home/work/banews-server/1/app/models/Comment.php(59): Phalcon\Mvc\Model::count(Array)
#22 /home/work/banews-server/1/app/controllers/NewsController.php(33): Comment::getCount('1001939')
#23 [internal function]: NewsController->DetailAction()
#24 [internal function]: Phalcon\Dispatcher->dispatch()
#25 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#26 {main}
[Sun, 08 May 16 15:16:17 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(24): UserController->postCollect()
#1 [internal function]: UserController->CollectAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#4 {main}
[Sun, 08 May 16 15:16:34 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(24): UserController->postCollect()
#1 [internal function]: UserController->CollectAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#4 {main}
[Sun, 08 May 16 15:16:44 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(24): UserController->postCollect()
#1 [internal function]: UserController->CollectAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#4 {main}
[Sun, 08 May 16 15:25:40 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/UserController.php(28): UserController->delCollect()
#1 [internal function]: UserController->CollectAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#4 {main}
[Sun, 08 May 16 15:26:01 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDO->exec('DELETE FROM tb_...')
#1 /home/work/banews-server/1/app/controllers/UserController.php(192): Phalcon\Db\Adapter\Pdo->execute('DELETE FROM tb_...')
#2 /home/work/banews-server/1/app/controllers/UserController.php(28): UserController->delCollect()
#3 [internal function]: UserController->CollectAction()
#4 [internal function]: Phalcon\Dispatcher->dispatch()
#5 /home/work/banews-server/1/public/index.php(53): Phalcon\Mvc\Application->handle()
#6 {main}
[Sun, 08 May 16 15:37:18 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDO->__construct('mysql:host=10.8...', 'root', 'MhxzKhl-Happy', Array)
#1 [internal function]: Phalcon\Db\Adapter\Pdo->connect(Array)
#2 /home/work/banews-server/1/app/config/services.php(40): Phalcon\Db\Adapter\Pdo->__construct(Array)
#3 [internal function]: {closure}()
#4 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#5 [internal function]: Phalcon\Di->get('db', NULL)
#6 [internal function]: Phalcon\Di->getShared('db')
#7 [internal function]: Phalcon\Mvc\Model\Manager->_getConnection(Object(Collect), NULL)
#8 [internal function]: Phalcon\Mvc\Model\Manager->getReadConnection(Object(Collect))
#9 [internal function]: Phalcon\Mvc\Model->getReadConnection()
#10 [internal function]: Phalcon\Mvc\Model\MetaData\Strategy\Introspection->getMetaData(Object(Collect), Object(Phalcon\Di\FactoryDefault))
#11 [internal function]: Phalcon\Mvc\Model\MetaData->_initialize(Object(Collect), 'collect-tb_coll...', 'tb_collect', '')
#12 [internal function]: Phalcon\Mvc\Model\MetaData->readMetaData(Object(Collect))
#13 [internal function]: Phalcon\Mvc\Model\MetaData->hasAttribute(Object(Collect), 'user_id')
#14 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array)
#15 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true)
#16 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array)
#17 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect()
#18 [internal function]: Phalcon\Mvc\Model\Query->parse()
#19 [internal function]: Phalcon\Mvc\Model\Query->execute()
#20 /home/work/banews-server/1/app/models/Collect.php(47): Phalcon\Mvc\Model::find(Array)
#21 /home/work/banews-server/1/app/controllers/UserController.php(160): Collect::getAll('24', '', '')
#22 /home/work/banews-server/1/app/controllers/UserController.php(26): UserController->getCollect()
#23 [internal function]: UserController->CollectAction()
#24 [internal function]: Phalcon\Dispatcher->dispatch()
#25 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#26 {main}
[Sun, 08 May 16 15:54:48 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDO->exec('DELETE FROM tb_...')
#1 /home/work/banews-server/1/app/controllers/UserController.php(192): Phalcon\Db\Adapter\Pdo->execute('DELETE FROM tb_...')
#2 /home/work/banews-server/1/app/controllers/UserController.php(28): UserController->delCollect()
#3 [internal function]: UserController->CollectAction()
#4 [internal function]: Phalcon\Dispatcher->dispatch()
#5 /home/work/banews-server/1/public/index.php(59): Phalcon\Mvc\Application->handle()
#6 {main}
[Mon, 09 May 16 12:17:00 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 12:17:26 +0800][NOTICE]: [HttpError]: #0 /home/work/banews-server/1/app/controllers/NewsController.php(77): BaseController->get_request_param('channel_id', 'int', true)
#1 [internal function]: NewsController->listAction()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#4 {main}
[Mon, 09 May 16 12:52:50 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\Db\Adapter\Pdo->executePrepared(Object(PDOStatement), Array, Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo->query('SELECT `tb_news...', Array, Array)
#3 [internal function]: Phalcon\Mvc\Model\Query->_executeSelect(Array, Array, Array)
#4 [internal function]: Phalcon\Mvc\Model\Query->execute()
#5 /home/work/banews-server/1/app/models/News.php(88): Phalcon\Mvc\Model::findFirst(Array)
#6 /home/work/banews-server/1/app/controllers/NewsController.php(86): News::getBySign(Array)
#7 [internal function]: NewsController->listAction()
#8 [internal function]: Phalcon\Dispatcher->dispatch()
#9 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#10 {main}
[Mon, 09 May 16 12:53:25 +0800][NOTICE]: [HttpError]: #0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\Db\Adapter\Pdo->executePrepared(Object(PDOStatement), Array, Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo->query('SELECT `tb_news...', Array, Array)
#3 [internal function]: Phalcon\Mvc\Model\Query->_executeSelect(Array, Array, Array)
#4 [internal function]: Phalcon\Mvc\Model\Query->execute()
#5 /home/work/banews-server/1/app/models/News.php(88): Phalcon\Mvc\Model::findFirst(Array)
#6 /home/work/banews-server/1/app/controllers/NewsController.php(86): News::getBySign(Array)
#7 [internal function]: NewsController->listAction()
#8 [internal function]: Phalcon\Dispatcher->dispatch()
#9 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#10 {main}
[Mon, 09 May 16 16:32:51 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:29 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:30 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:31 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:32 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:33 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:34 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:35 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:57 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:58 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:59 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
[Mon, 09 May 16 16:36:59 +0800][NOTICE]: [HttpError]: #0 [internal function]: NewsController->listAction()
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /home/work/banews-server/1/public/index.php(58): Phalcon\Mvc\Application->handle()
#3 {main}
